version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'flask_db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
